# Generated by Django 5.0.3 on 2024-04-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(upload_to='foods/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.IntegerField(verbose_name='زمان آماده سازی'),
        ),
    ]
