# Generated by Django 5.0.3 on 2024-04-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_photo_alter_food_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(upload_to='foods/', verbose_name='عکس غذا'),
        ),
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.IntegerField(verbose_name='زمان لازم'),
        ),
    ]
